/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as AboutRouteImport } from './routes/about';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index';
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile';
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses';
import { Route as AuthenticatedCreate_expenseRouteImport } from './routes/_authenticated/create_expense';
const AboutRoute = AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => rootRouteImport,
});
const AuthenticatedRoute = AuthenticatedRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => rootRouteImport,
});
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedCreate_expenseRoute = AuthenticatedCreate_expenseRouteImport.update({
    id: '/create_expense',
    path: '/create_expense',
    getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedRouteChildren = {
    AuthenticatedCreate_expenseRoute: AuthenticatedCreate_expenseRoute,
    AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
    AuthenticatedProfileRoute: AuthenticatedProfileRoute,
    AuthenticatedIndexRoute: AuthenticatedIndexRoute,
};
const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren);
const rootRouteChildren = {
    AuthenticatedRoute: AuthenticatedRouteWithChildren,
    AboutRoute: AboutRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
